name: guccione-browser-search
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: FabriGu/guccione-browser-search
    build_command: |
      npm ci
      mkdir -p models/huggingface
      export TRANSFORMERS_CACHE=$(pwd)/models/huggingface
      node scripts/download-models.js
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
      - key: TRANSFORMERS_CACHE
        value: /app/models/huggingface
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-s
    git:
      git_lfs: true