# app.yaml
name: guccione-browser-search
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: FabriGu/guccione-browser-search
    build_command: |
      npm ci
      mkdir -p models/huggingface
      mkdir -p data
      # Skip model download at build time to avoid timeouts
    run_command: |
      export TRANSFORMERS_CACHE=/app/models/huggingface
      export NODE_OPTIONS="--max-old-space-size=4096"
      npm start
    envs:
      - key: NODE_ENV
        value: production
      - key: TRANSFORMERS_CACHE
        value: /app/models/huggingface
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxl
    git:
      git_lfs: true