# app.yaml
name: guccione-browser-search
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: FabriGu/guccione-browser-search
    build_command: |
      npm ci
      mkdir -p models/huggingface
      mkdir -p data
      export TRANSFORMERS_CACHE=$(pwd)/models/huggingface
      echo "Running download-all-models script..."
      node scripts/download-all-models.js
      echo "Download complete"
    run_command: |
      export TRANSFORMERS_CACHE=/app/models/huggingface
      npm start
    envs:
      - key: NODE_ENV
        value: production
      - key: TRANSFORMERS_CACHE
        value: /app/models/huggingface
      # Add memory limit environment variable to avoid OOM errors
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
    http_port: 3000
    # Increase instance size to handle model loading
    instance_count: 1
    instance_size_slug: basic-xxl
    git:
      git_lfs: true